### ISSUE TITLE
Enviar tarea a git de Webscraping

### ISSUE THREAD

**Issue by enriques76** [GeorgeAdrock/webScrapping#4]
Jorge, cómo estás.
Recuerda que debemos trabajar desde las Folders de Git del curso. 
La tarea veo que está en tu perfil, pero no como fork de una carpeta en la raíz de pescapil/WebScraping...

**Comment by GeorgeAdrock** [comment]
Estupendo estimado, lo haremos a su debido tiempo.
la idea ahora es que puedan correr el proyecto en sus máquinas.  y comenzamos con la documentación y mejora sobre el scrapeo de la página
